<a href="https://colab.research.google.com/github/fathimahiba7369-arch/AI-ML/blob/main/day4/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)

Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [3]:
arr = np.arange(1, 10)

new_arr = arr.reshape(3, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr = np.array([10, 20, 5, 8])

print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))


Maximum: 20
Minimum: 5


In [6]:
arr = np.random.randint(1, 100, 5)

print(arr)

[11 21 34  9 13]
